routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerTypeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    Route::resource('/produtos', ProductController::class);
    Route::resource('/customer-type', CustomerTypeController::class);
    Route::resource('/clientes', CustomerController::class);
    Route::resource('pedidos', OrderController::class);
    Route::delete('order-items/{id}', [OrderController::class, 'destroyOrderItem'])->name('orderItems.destroy');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/clientes/create.blade.php
<x-app-layout>
{{-- header abaixo do menu --}}
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Clientes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">

                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Clientes</title>
                    </head>
                                       
                    <body>
                        @include('layouts.bootstrap')
                        <h1>Criar Cliente</h1>

                        <form action="/clientes" method="POST">
                            @csrf

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Nome:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="name" id="nome" class="form-control" required placeholder="Nome Cliente">
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>CPF/ CNPJ:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="cpf_cnpj" id="document" class="cpfOuCnpj form-control" required placeholder="CPF/ CNPJ">
                                    </div>
                                    <br>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>CEP:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="zip_code" class="form-control zip_code" required placeholder="Informe o CEP">
                                    </div>
                                </div>
                               
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Rua:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="address" class="form-control address" required >
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Número:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="number" class="form-control" required >
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Bairro:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="district" class="form-control district" required >
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Complemento:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="complement" class="form-control" required >
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Cidade:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="city" class="form-control city" required >
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Estado:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="state" class="form-control state" required >
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Tipo de Cliente:</strong>
                                        <select class="js-example-basic-single form-select form-select-solid" name="type_id">
                                            <option value="" selected hidden>Selecione um Tipo de cliente</option>
                                            @foreach ($customerType as $ct)
                                                <option value="{{ $ct->id }}" {{ (isset($cliente) && $ct->id == $cliente->type->id) || $ct->id == old('terminal_id') ? 'selected' : '' }}>
                                                    {{ $ct->description }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-success m-2">Salvar</button>
                                    <a  href="{{ route('clientes.index') }}" class="m-2 btn btn-light me-3">Cancelar</a>
                                </div>
                            </div>

                        </form>
                    </body>

                    </html>
                </div>
            </div>
        </div>
    </div>

<script>
    var options = {
    onKeyPress: function (cpf, ev, el, op) {
        var masks = ['000.000.000-000', '00.000.000/0000-00'];
        $('.cpfOuCnpj').mask((cpf.length > 14) ? masks[1] : masks[0], op);
    }
}

$('.cpfOuCnpj').length > 11 ? $('.cpfOuCnpj').mask('00.000.000/0000-00', options) : $('.cpfOuCnpj').mask('000.000.000-00#', options);

$(document).on('blur', '.zip_code', function (e){
    e.preventDefault();
    var cep = $(this).val();

    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados)

    {
        if(!("erro" in dados)) {
            //Atualiza os campos com o valor da consulta;
            $(".address").val(dados.logradouro);
            $(".district").val(dados.bairro);
            $(".city").val(dados.localidade);
            $(".state").val(dados.uf);
            
        } else {
            $(".address").val('');
            $(".district").val('');
            $(".city").val('');
            $(".state").val('');
        }
    }
);


});
</script>
    

</x-app-layout>

resources/views/clientes/edit.blade.php
<x-app-layout>
    
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Clientes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    
                    @include('layouts.bootstrap')
                    <form action="/clientes/{{$cliente->id}}" method="POST">
                        @csrf
                        @method('PUT')
                    
                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Nome:</strong>
                                    <input type="text" name="name" id="name" class="form-control" value="{{$cliente->name}}">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>CPF/ CNPJ:</strong>
                                    <input type="text" name="cpf_cnpj" id="cpf_cnpj" class="form-control cpfOuCnpj" value="{{$cliente->cpf_cnpj}}">
                                </div>
                                <br>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>CEP:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="zip_code" class="form-control zip_code" required placeholder="Informe o CEP"
                                    value="{{ $cliente->zip_code }}">
                                </div>
                            </div>
                           
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Rua:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="address" class="form-control address" required value="{{ $cliente->address }}">
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Número:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="number" class="form-control" required value="{{ $cliente->number }}">
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Bairro:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="district" class="form-control district" required value="{{ $cliente->district }}" >
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Complemento:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="complement" class="form-control" required value="{{ $cliente->complement }}">
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Cidade:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="city" class="form-control city" required value="{{ $cliente->city }}">
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Estado:</strong>
                                    <span class="text-danger">*</span>
                                    <input type="text" name="state" class="form-control state" required value="{{ $cliente->state }}">
                                </div>
                            </div>
                           
                            <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-success m-2">Salvar</button>
                                <a  href="{{ route('clientes.index') }}" class="m-2 btn btn-light me-3">Voltar</a>
                            </div>
                        </div>
                        
                        </form>
                    </html>
                </div>
            </div>
        </div>
    </div>

    <script>
        var options = {
        onKeyPress: function (cpf, ev, el, op) {
            var masks = ['000.000.000-000', '00.000.000/0000-00'];
            $('.cpfOuCnpj').mask((cpf.length > 14) ? masks[1] : masks[0], op);
        }
    }
    
    $('.cpfOuCnpj').length > 11 ? $('.cpfOuCnpj').mask('00.000.000/0000-00', options) : $('.cpfOuCnpj').mask('000.000.000-00#', options);
    </script>
</x-app-layout>

resources/views/clientes/index.blade.php
<x-app-layout>
    
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Clientes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">
                        
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Clientes</title>
                    </head>
                    @include('layouts.bootstrap')
                    <div class="d-flex justify-content-end">
                        <a class="btn btn-success" href="/clientes/create"><i class="fa-solid fa-plus"></i></a>
                    </div>                    
                    
                    <body>
                        <h1>Listagem de Clientes</h1>
                        <table class="table table-bordered">
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>CPF/ CNPJ</th>
                                <th width="280px">Açoes</th>
                            </tr>
                            @foreach ($clientes as $cliente)
                            <tr>
                                <td>{{ $cliente->id}}</td>
                                <td>{{ $cliente->name }}</td>
                                <td>{{ $cliente->cpf_cnpj }}</td>
                                <td>
                                    <form action="{{ route('clientes.destroy',$cliente->id) }}" method="POST">
                       
                                        <a class="btn btn-info" href="{{ route('clientes.show',$cliente->id) }}"><i class="fa-solid fa-eye"></i></a>
                        
                                        <a class="btn btn-primary" href="{{ route('clientes.edit',$cliente->id) }}"><i class="fa-solid fa-pen"></i></a>
                       
                                        @csrf
                                        @method('DELETE')
                          
                                        <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>                       
                                            
                    </body>
                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/clientes/show.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Detalhe Cliente') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">

                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Clientes</title>
                    </head>

                    <a class="d-flex justify-content-end" href="/Clientes/create">Criar Novo Cliente</a>

                    <body>
                        @include('layouts.bootstrap')
                        <h1>Detalhes do Cliente</h1>
                        <p>Nome: {{ $cliente->name}}</p>
                        <p>CPF/ CNPJ: {{ $cliente->cpf_cnpj}}</p>
                        
                        <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                            <a class="m-2 btn btn-primary me-3" href="/Clientes/{{$cliente->id}}/edit">Editar</a>
                            <a  href="{{ route('clientes.index') }}" class="m-2 btn btn-light me-3">Voltar</a>
                        </div>
                        
                    </body>

                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>