routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerTypeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    Route::resource('/produtos', ProductController::class);
    Route::resource('/customer-type', CustomerTypeController::class);
    Route::resource('/clientes', CustomerController::class);
    Route::resource('pedidos', OrderController::class);
    Route::delete('order-items/{id}', [OrderController::class, 'destroyOrderItem'])->name('orderItems.destroy');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/Models/Produto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    use HasFactory;

    protected $fillable = [
        'nome',
        'preco'
    ];
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/produtos/create.blade.php
<x-app-layout>
{{-- header abaixo do menu --}}
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Produtos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">

                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Produtos</title>
                    </head>
                                       
                    <body>
                        @include('layouts.bootstrap')
                        <h1>Criar Produto</h1>

                        <form action="/produtos" method="POST">
                            @csrf

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Nome:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="nome" id="nome" class="form-control" required placeholder="Descrição">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Preço:</strong>
                                        <span class="text-danger">*</span>
                                        <input type="text" name="preco" id="preco" class="form-control" required placeholder="Preço">
                                    </div>
                                    <br>
                                </div>
                               
                                <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                                    <button type="submit" class="btn btn-success m-2">Salvar</button>
                                    <a  href="{{ route('produtos.index') }}" class="m-2 btn btn-light me-3">Cancelar</a>
                                </div>
                            </div>

                        </form>
                    </body>

                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/produtos/edit.blade.php
<x-app-layout>
    
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Produtos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    
                    @include('layouts.bootstrap')
                    <form action="/produtos/{{$produto->id}}" method="POST">
                        @csrf
                        @method('PUT')
                    
                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Nome:</strong>
                                    <input type="text" name="nome" id="nome" class="form-control" placeholder="Descrição" value="{{$produto->nome}}">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Preço:</strong>
                                    <input type="text" name="preco" id="preco" class="form-control" placeholder="Preço" value="{{$produto->preco}}">
                                </div>
                                <br>
                            </div>
                           
                            <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-success m-2">Salvar</button>
                                <a  href="{{ route('produtos.index') }}" class="m-2 btn btn-light me-3">Voltar</a>
                            </div>
                        </div>
                        
                        </form>
                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/produtos/index.blade.php
<x-app-layout>
    
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Produtos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">
                        
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Produtos</title>
                    </head>
                    @include('layouts.bootstrap')
                    <div class="d-flex justify-content-end">
                        <a class="btn btn-success" href="/produtos/create"><i class="fa-solid fa-plus"></i></a>
                    </div>                    
                    
                    <body>
                        <h1>Listagem de Produtos</h1>
                        <table class="table table-bordered">
                            <tr>
                                <th>Id</th>
                                <th>Descrição</th>
                                <th>Preço</th>
                                <th width="280px">Açoes</th>
                            </tr>
                            @foreach ($produtos as $produto)
                            <tr>
                                
                                <td>{{ $produto->id}}</td>
                                <td>{{ $produto->nome }}</td>
                                <td>{{ $produto->preco }}</td>
                                <td>
                                    <form action="{{ route('produtos.destroy',$produto->id) }}" method="POST">
                       
                                        <a class="btn btn-info" href="{{ route('produtos.show',$produto->id) }}"><i class="fa-solid fa-eye"></i></a>
                        
                                        <a class="btn btn-primary" href="{{ route('produtos.edit',$produto->id) }}"><i class="fa-solid fa-pen"></i></a>
                       
                                        @csrf
                                        @method('DELETE')
                          
                                        <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>                       
                                            
                    </body>
                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/produtos/show.blade.php
</html>
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Detalhe Produto') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">

                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Produtos</title>
                    </head>

                    <a class="d-flex justify-content-end" href="/produtos/create">Criar Novo Produto</a>

                    <body>
                        @include('layouts.bootstrap')
                        <h1>Detalhes do Produto</h1>
                        <p>Nome: {{ $produto->nome}}</p>
                        <p>Preço: {{ $produto->preco}}</p>
                        
                        <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                            <a class="m-2 btn btn-primary me-3" href="/produtos/{{$produto->id}}/edit">Editar</a>
                            <a  href="{{ route('produtos.index') }}" class="m-2 btn btn-light me-3">Voltar</a>
                        </div>
                        
                    </body>

                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>