routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerTypeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    Route::resource('/produtos', ProductController::class);
    Route::resource('/customer-type', CustomerTypeController::class);
    Route::resource('/clientes', CustomerController::class);
    Route::resource('pedidos', OrderController::class);
    Route::delete('order-items/{id}', [OrderController::class, 'destroyOrderItem'])->name('orderItems.destroy');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/pedidos/create.blade.php
<x-app-layout>
    {{-- header abaixo do menu --}}
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Produtos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">

                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Produtos</title>
                    </head>

                    <body>
                        @include('layouts.bootstrap')
                        <h1>Criar Pedido</h1>

                        <form action="{{ route('pedidos.store') }}" method="POST">
                            @csrf

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Cliente:</strong>
                                        <select class="js-example-basic-single form-select form-select-solid" name="customer_id">
                                            <option value="" selected hidden>Selecione um cliente</option>
                                            @foreach ($customers as $customer)
                                            <option value="{{ $customer->id }}">{{ $customer->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <strong>Produtos:</strong>
                                        <div>
                                            @foreach($produtos as $produto)
                                            <div class="row mb-2">
                                                <div class="col-md-4">
                                                    <input type="checkbox" name="produtos[{{ $produto->id }}][id]" value="{{ $produto->id }}">
                                                    <span class="m-2">{{ $produto->nome }}</span>
                                                </div>
                                                <div class="col-md-4">
                                                    <input type="number" class="form-control" name="produtos[{{ $produto->id }}][amount]" placeholder="Quantidade">
                                                </div>
                                            </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-success m-2">Salvar</button>
                                <a href="{{ route('pedidos.index') }}" class="m-2 btn btn-light me-3">Cancelar</a>
                            </div>
                        </form>
                    </body>

                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/pedidos/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editar Pedido') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    @include('layouts.bootstrap')
                    <h1>Editar Pedido</h1>

                    <form action="{{ route('pedidos.update', $pedido->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Cliente:</strong>
                                    <select class="js-example-basic-single form-select form-select-solid" name="customer_id" readonly>
                                        <option value="" selected hidden>Selecione um cliente</option>
                                        @foreach ($customers as $customer)
                                            <option value="{{ $customer->id }}" @if($pedido->customer_id == $customer->id) selected @endif>{{ $customer->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <strong>Produtos:</strong>
                                    <div>
                                        @foreach($produtos as $produto)
                                            <div class="row mb-2">
                                                <div class="col-md-4">
                                                    <input type="checkbox" name="produtos[{{ $produto->id }}][id]" value="{{ $produto->id }}" 
                                                    @if($pedido->items->contains('product_id', $produto->id)) checked @endif>
                                                    <span class="m-2">{{ $produto->nome }}</span>
                                                    <input type="hidden" name="produtos[{{ $produto->id }}][amount]" value="{{ $pedido->items->firstWhere('product_id', $produto->id)->amount ?? 0 }}">
                                                    <input type="hidden" name="produtos[{{ $produto->id }}][delete]" value="0">
                                                </div>
                                                <div class="col-md-4">
                                                    <input type="number" class="form-control" name="produtos[{{ $produto->id }}][amount]" placeholder="Quantidade"
                                                    value="{{ $pedido->items->firstWhere('product_id', $produto->id)->amount ?? 0 }}">
                                                </div>
                                                <div class="col-md-4">
                                                    @if($pedido->items->contains('product_id', $produto->id))
                                                        <a href="#" class="btn btn-danger" onclick="deleteItem('{{ $pedido->items->firstWhere('product_id', $produto->id)->id }}')">Excluir</a>
                                                    @endif
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex justify-content-end col-xs-12 col-sm-12 col-md-12">
                            <button type="submit" class="btn btn-success m-2">Salvar</button>
                            <a href="{{ route('pedidos.index') }}" class="m-2 btn btn-light me-3">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        function deleteItem(itemId) {
            if (confirm('Tem certeza que deseja excluir este item?')) {
                fetch(`{{ url('order-items') }}/${itemId}`, {  // Correção na URL
                    method: 'DELETE',
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}',
                        'Content-Type': 'application/json',
                        'Accept': 'application/json'
                    },
                })
                .then(response => {
                    // Recarrega a página após a exclusão bem-sucedida
                    location.reload();
                })
                .catch(error => {
                    console.error('Erro:', error);
                    alert('Erro ao excluir o item');
                });
            }
        }
    </script>
</x-app-layout>

resources/views/pedidos/index.blade.php
<x-app-layout>
    
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Pedidos') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <!DOCTYPE html>
                    <html lang="en">
                        
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                        <title>Listagem de Pedidos</title>
                    </head>
                    @include('layouts.bootstrap')
                    <div class="d-flex justify-content-end">
                        <a class="btn btn-success" href="/pedidos/create"><i class="fa-solid fa-plus"></i></a>
                    </div>                    
                    
                    <body>
                        <h1>Listagem de Pedidos</h1>
                        <table class="table table-bordered">
                            <tr>
                                <th>Id</th>
                                <th>Cliente</th>
                                <th>Total</th>
                                <th width="280px">Açoes</th>
                            </tr>
                            @foreach ($pedidos as $pedido)
                            <tr>
                                
                                <td>{{ $pedido->id }}</td>
                                <td>{{ $pedido->customer->name }}</td>
                                <td>{{ $pedido->total }}</td>
                                <td>
                                    <form action="{{ route('pedidos.destroy',$pedido->id) }}" method="POST">
                       
                                        <a class="btn btn-info" href="{{ route('pedidos.show', $pedido->id) }}"><i class="fa-solid fa-eye"></i></a>
                        
                                        <a class="btn btn-primary" href="{{ route('pedidos.edit',$pedido->id) }}"><i class="fa-solid fa-pen"></i></a>
                       
                                        @csrf
                                        @method('DELETE')
                          
                                        <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>                       
                                            
                    </body>
                    </html>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/pedidos/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Detalhes do Pedido') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    @include('layouts.bootstrap')
                    <h1>Detalhes do Pedido</h1>

                    <p><strong>ID:</strong> {{ $pedido->id }}</p>
                    <p><strong>Cliente:</strong> {{ $pedido->customer->name }}</p>
                    <p><strong>Total:</strong> {{ $pedido->total }}</p>

                    <h2>Itens do Pedido</h2>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Quantidade</th>
                                <th>Preço</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pedido->items as $item)
                                <tr>
                                    <td>{{ $item->product->nome }}</td>
                                    <td>{{ $item->amount }}</td>
                                    <td>{{ $item->price }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <a href="{{ route('pedidos.index') }}" class="btn btn-secondary">Voltar</a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>